version: '3'
services:
  ravelights-backend:
    container_name: ravelights-backend
    build: ../ravelights
    network_mode: "host"
    command: python3 src/main.py
  ravelights-frontend:
    container_name: ravelights-frontend
    build: ../ravelights-ui
    network_mode: "host"
