version: '3'
services:
  ravelights-backend:
    container_name: ravelights-backend
    build: ../ravelights
    network_mode: "host"
    command: python3 main.py --no-webui --artnet-serial --no-visualizer
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
  ravelights-frontend:
    container_name: ravelights-frontend
    build: ../ravelights-ui
    network_mode: "host"
